pub(crate) mod addressing;
pub mod allocator;
pub mod attachment;
pub mod bpf;
pub mod controller;
pub mod discovery;
#[cfg(target_os = "linux")]
pub(crate) mod embedded_bpf;
pub mod events;
pub mod gossip;
pub mod lb;
pub(crate) mod naming;
pub mod nodeport;
pub mod registry;
pub mod service;
pub mod transition;
pub mod types;
pub mod wireguard;
